name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input for the main workflow'
        required: false
        default: 'default main value'

jobs:
  trigger-target-workflow:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Target Workflow
        id: trigger
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # ターゲットワークフローをトリガー（inputとしてmainのinputを渡す）
          gh workflow run target-workflow.yml --ref main --json id -q '.id' \
            --field example_input="${{ github.event.inputs.example_input }}"

          sleep 10

          # トリガーされたワークフローのIDを取得
          workflow_run_id=$(gh run list --workflow=target-workflow.yml --branch=main --limit=1 --json databaseId -q '.[0].databaseId')
          echo "Triggered Workflow Run ID: $workflow_run_id"
          echo "WORKFLOW_RUN_ID=$workflow_run_id" >> $GITHUB_ENV

          # ワークフローの実行を監視
          gh run watch $workflow_run_id= --exit-status

      - name: Show Target Workflow Logs
        if: success() # ターゲットワークフローが成功した場合
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # トリガーされたワークフローのログを表示
          gh run view $WORKFLOW_RUN_ID --log
