name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input for the main workflow'
        required: false
        default: 'default main value'

jobs:
  trigger-target-workflow:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Target Workflow
        id: trigger
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # ターゲットワークフローをトリガー（inputとしてmainのinputを渡す）
          gh workflow run target-workflow.yml --ref main --field example_input="${{ github.event.inputs.example_input }}"
          
          # トリガーされたワークフローのIDを取得
          TARGET_RUN_ID=$(gh run list --workflow=target-workflow.yml --branch=main --limit=1 --json databaseId -q '.[0].databaseId')
          echo "Triggered Workflow Run ID: $TARGET_RUN_ID"
          echo "TARGET_RUN_ID=$TARGET_RUN_ID" >> $GITHUB_ENV

          # ワークフローの実行を監視
          gh run watch $TARGET_RUN_ID --exit-status

      - name: Show Target Workflow Logs
        if: success() # ターゲットワークフローが成功した場合
        run: |
          # トリガーされたワークフローのログを表示
          gh run view $TARGET_RUN_ID --log
